### ISSUE TITLE
installation of the csv-preview tool

### ISSUE THREAD

**Issue by jaykayone** [opendatalu/gouvlu#106]
can you point us to an instruction about how to install the csv preview tool  please?

**Comment by noirbizarre** [comment]
This is not "**a**" csv preview tool but:
- a preview feature in `udata`
- multiple plugins exposing previews

The preview feature is enabled by default using the [`PREVIEW_MODE`](https://udata.readthedocs.io/en/stable/adapting-settings/#preview_mode) setting.

Currently, the following plugins are exposing previews:
- `udata-ods` exposes OpenDataSoft previews (API Widgets) for harvested datasets
- `udata-geoplatform` exposes geo.data.gouv.fr previews for Inspire datasets
- [`udata-tabular-preview`](https://github.com/opendatateam/udata-tabular-preview) exposes simple generic previews for tabular files (ie. csv, xls...) using a [`csvapi`](https://github.com/opendatateam/csvapi) instance

More are coming, and any plugin can expose new previews.

If you only want a generic CSV preview, just use the [`udata-tabular-preview`](https://github.com/opendatateam/udata-tabular-preview) but there is some limitations:
- can only handle files under a specific size (depends on the server hosting the `csvapi` instance)
- can only preview well formatted CSV as well as raw xls, xlsx files (no macros, no style...)
