### ISSUE TITLE
Bug: Results paginator (Reuse) allows to advance to empty results set

### ISSUE THREAD

**Issue by petzlux** [opendatalu/gouvlu#12]

**Comment by noirbizarre** [comment]
Should have been fixed in upstream udata

**Comment by petzlux** [comment]
When on last page of a result set (tried it with dataset list) , on can click and advance another page.

**Comment by petzlux** [comment]
Go to https://demoprod.data.public.lu/fr/datasets/?page=29  and then click Next Result Page `>`

**Comment by petzlux** [comment]
Still not working on latest udata release ?

**Comment by petzlux** [comment]
Still valid bug .

**Comment by petzlux** [comment]
https://github.com/opendatateam/udata/issues/1534
