### ISSUE TITLE
Govbar missing

### ISSUE THREAD

**Issue by petzlux** [opendatalu/gouvlu#28]
As a requirement for all gouv.lu sites, we have to include the govbar in the header (see existing data.public.lu) . Easiest and most consistent way to do this is through linking external css ...

**Comment by noirbizarre** [comment]
OK, it was adblocked on my computer (so I just seen it for the first time now).
Do you have some documentation about it ?

**Comment by petzlux** [comment]
This is all we got as documentation about it, the required files you have to find from our old design template ... 

Required files

HTML code
assets/css/govbar.css
assets/img/header/gov-light.png
Place the HTML code of the Govbar immediately following the <body> tag.
The language of the static Govbar is not linked to the lang="fr" attribute of the <html> tag. You will have to operate the language change in your app.
In the HTML code in attachment you will find all the needed translations for the Govbar.

Example page including the Govbar

**Comment by petzlux** [comment]
@noirbizarre Here you can find the CSS and JS file, if thats useful 

https://github.com/Geoportail-Luxembourg/main/pull/140/commits/ba3c73a175462bf92a2750b677a9ce485becac40

**Comment by petzlux** [comment]
Here is a more up to date version ... 

Avant le tag body :
 ````
<script src="//cdn.public.lu/skizz/govbar/2-2-0/govbar.js" data-govbar="{ }"></script>
<script>govbar();</script>
 ````
Dans les CSS :
 ````
/****************** GOVBAR *****************************/
@media only screen and (min-width: 20em) {
.govbar {
  background: #fff;
  border-bottom: 1px solid #cccaca;
  font-family: Arial, sans-serif;
  font-size: 12px;
  position: relative;
  z-index: 30000;
}
.govbar:before,
.govbar:after {
  content: '';
  display: table;
}
.govbar:after {
  clear: both;
}
.govbar--light {
  background: #fff;
}
.govbar-link,
.govbar-link:visited,
.govbar-link:focus,
.govbar-link:hover {
  color: #222 !important;
}
.govbar-link:hover,
.govbar-link:focus {
  background: #e6e6e6;
}
.govbar-logo {
  border: 0;
  display: block;
  padding: 3px 8px;
  vertical-align: middle;
}
.govbar-logo img {
  border: 0;
  display: block;
  height: 40px;
}
.govbar-links {
  display: none;
  list-style: none;
  margin: 0;
  padding: 0;
}
.govbar-link {
  border: 0;
  border-top: 1px solid #ddd;
  display: block;
  font-weight: bold;
  padding: 8px;
  text-decoration: none;
}
.govbar-more {
  font-weight: normal;
}
}
@media only screen and (min-width: 45em) {
.govbar-logo {
  float: left;
}
.govbar-links {
  display: block;
  float: right;
  line-height: 30px;
}
.govbar-links li {
  float: left;
}
.govbar-link {
  border-top: 0;
  float: left;
  min-height: 30px;
}
}
````
